import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import bg from "@/src/img/background.png";
import logo from "@/src/img/cmd-logo.png";
import Image from "next/image";
import { Inter, Viga } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const viga = Viga({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-viga",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body
        className={`${inter.variable} ${viga.variable} antialiased min-h-full flex flex-col`}
      >
        <div
          className="min-w-full h-screen bg-cover bg-center font-inter overflow-scroll py-10"
          style={{ backgroundImage: `url(${bg.src})` }}
        >
          <div className="pl-[50px] pt-[10px] flex items-end">
            <Image
              src={logo}
              width={120}
              height={120}
              alt="Picture of the author"
            />
            <h1 className="font-viga text-[40px] mb-[-10px] font-bold text-gray-900">
              CAPELLA MULTIDANA
            </h1>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
